### ISSUE TITLE
Whisper-v3

### ISSUE THREAD

**Issue by suryasanchez** [thomasmol/cog-whisper-diarization#1]
Update to support Whisper v3? https://github.com/openai/whisper/discussions/1762

**Comment by thomasmol** [comment]
Yes I am working on it. Currently there are issues converting whisper v3 to cttranslate https://github.com/guillaumekln/faster-whisper/issues/544#issuecomment-1802818862

**Comment by thomasmol** [comment]
Currently waiting on this PR to get merged: https://github.com/huggingface/transformers/pull/26699 so we can use batched inference and still get word level timestamps. I'll move away from faster-whisper (the maintainer is now working at Apple and not actively maintaining the repo anymore) and use the hugginface/transformer implementation described here: https://huggingface.co/openai/whisper-large-v3. Should result in even faster inference over faster-whisper. Hopefully somewhere this or next week!

**Comment by thomasmol** [comment]
Faster-whisper 0.10.0 was released, which includes support for whisper v3. Faster-whisper also has a new maintainer and moved here: https://github.com/SYSTRAN/faster-whisper.
Just updated the pipeline to new version of faster-whisper and to new version of pyannote (3.1). 
Will still look into the batched inference when that's possible, but only when it supports VAD and word level timestamps.
