### ISSUE TITLE
HuggingFace API Key

### ISSUE THREAD

**Issue by danielsantiago** [thomasmol/cog-whisper-diarization#10]
Hello,

First of all, thanks for the implementation. I'm trying to deploy some changes to my Replicate account but it's asking me for the HuggingFace API Key. I am deploying from github actions, where or how can I add this API Key so that it works in Replicate?

The error in Replicate:
```Could not download 'pyannote/speaker-diarization-3.1' pipeline.
It might be because the pipeline is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:
>>> Pipeline.from_pretrained('pyannote/speaker-diarization-3.1',
...                          use_auth_token=YOUR_AUTH_TOKEN)
If this still does not work, it might be because the pipeline is gated:
visit https://hf.co/pyannote/speaker-diarization-3.1 to accept the user conditions.
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cog/server/worker.py", line 185, in _setup
run_setup(self._predictor)
File "/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cog/predictor.py", line 70, in run_setup
predictor.setup()```

**Comment by thomasmol** [comment]
you need to use your own huggingface token. i think this is possible with github actions. you probably need to add your token to the environment of your repo: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions
