### ISSUE TITLE
Cog looping without logs

### ISSUE THREAD

**Issue by MaximeDde** [thomasmol/cog-whisper-diarization#12]
Hey @thomasmol , as usual, thanks for this model ! 

Just wanted to share my recent experience on the cog on Replicate, which seems to have several infinite loops going on, for a reason I couldn't find since it just started today...! Has anything similar happened, or is known to you at the moment ?

**Comment by thomasmol** [comment]
Tbh i haven't seen that. I'd check the Cog github repo and report the issue there: https://github.com/replicate/cog
