### ISSUE TITLE
How to run openapi /predictions

### ISSUE THREAD

**Issue by d8rt8v** [thomasmol/cog-whisper-diarization#15]
I want to run predictions via web API, not CLI.

Yet, when executing /predictions with this body I get the 422 error ` "msg": "'' is not a valid URL scheme. 'data', 'http', or 'https' is supported."` 

```
{
  "input": {
    "file_string": "",
    "file_url": "",
    "file": "/src/audio/audio.mp3",
    "group_segments": true,
    "transcript_output_format": "both",
    "num_speakers": 50,
    "translate": false,
    "language": "en",
    "prompt": "",
    "offset_seconds": 0
  },
  "id": "string",
  "created_at": "2024-08-19T09:34:43.940Z",
  "output_file_prefix": "test",
  "webhook": "string",
  "webhook_events_filter": [
    "start",
    "output",
    "logs",
    "completed"
  ]
}
```

When appending `data:// to "/src/audio/audio.mp3` ,e.g `data://src/audio/audio.mp3` or `data:///src/audio/audio.mp3`

I get `"msg": "not enough values to unpack (expected 2, got 1)",` 

The datafolder and files are available in container, plus the /health-check reports Ready.

**Comment by d8rt8v** [comment]
Also, when running with your file example from Replicate i get `"msg": "invalid or missing URL scheme"`

```
{
  "input": {
    "file_string": "",
    "file_url": "",
    "file": "https://replicate.delivery/pbxt/JcL0ttZLlbchC0tL9ZtB20phzeXCSuMm0EJNdLYElgILoZci/AI%20should%20be%20open-sourced.mp3",
    "group_segments": true,
    "transcript_output_format": "both",
    "num_speakers": 50,
    "translate": false,
    "language": "en",
    "prompt": "",
    "offset_seconds": 0
  },
  "id": "string",
  "created_at": "2024-08-19T09:34:43.940Z",
  "output_file_prefix": "string",
  "webhook": "string",
  "webhook_events_filter": [
    "start",
    "output",
    "logs",
    "completed"
  ]
}
```

**Comment by thomasmol** [comment]
can you tell me the URL you are making the request to? 

this is what a http request should look like: 
```bash
curl --silent --show-error https://api.replicate.com/v1/predictions \
	--request POST \
	--header "Authorization: Bearer $REPLICATE_API_TOKEN" \
	--header "Content-Type: application/json" \
	--data @- <<-EOM
{
	"version": "aae6db69a923a6eab6bc3ec098148a8c9c999685be89f428a4a6072fca544d26",
	"input": {
      "file": "https://replicate.delivery/pbxt/JcL0ttZLlbchC0tL9ZtB20phzeXCSuMm0EJNdLYElgILoZci/AI%20should%20be%20open-sourced.mp3",
      "prompt": "LLama, AI, Meta.",
      "file_url": "",
      "language": "en",
      "num_speakers": 2
	}
}
EOM
```

i think you need to have `https://` in the url, it cannot be just `api.replicate.com/v1/predictions`

**Comment by d8rt8v** [comment]
@thomasmol I tried to use `http://localhost:port/docs#/default/predict_predictions_post`

Now i managed to use predictions via curl on my localhost like [here](https://replicate.com/thomasmol/whisper-diarization/examples?input=docker)

Still i dont understand why using fastapi directly  on `/docs` refuses to work :) 

And thanks for the awesome product!
