### ISSUE TITLE
Hugging Face token

### ISSUE THREAD

**Issue by vladimarius** [thomasmol/cog-whisper-diarization#17]
I am testing this cog on Replicate and couldn't understand poor speaker diarization quality.
So it looks like it doesn't use any HuggingFace token since you have this in your settings:
https://github.com/thomasmol/cog-whisper-diarization/blob/6804be4405773cea3e728fae450d2ff662ebbfaa/predict.py#L36

I could easy submit a PR for this, but I don't understand why it's there from the start. 
Could you be so kind to explain that ?

**Comment by thomasmol** [comment]
Yes please do this to use the cog in your own environments:
- Accept [pyannote/segmentation-3.0](https://hf.co/pyannote/segmentation-3.0) user conditions
- Accept [pyannote/speaker-diarization-3.1](https://hf.co/pyannote/speaker-diarization-3.1) user conditions
- Create access token at [hf.co/settings/tokens](https://hf.co/settings/tokens).

Add your token to the cog and publish to replicate or run locally.

The live version on Replicate uses pyannote to create diarization, just using my own HF token. 
(I remove my token every time I commit new code then add it back to publish the container to Replicate)

I believe cog + replicate now has support for env vars, so i'll have to update this cog to use that.

**Comment by vladimarius** [comment]
Thank you
I think you could use HF token as a string parameter to cog, do not see a single reason not to do that

**Comment by thomasmol** [comment]
I am assuming you mean as an input parameter? That is certainly possible, however I specifically opted not to do that to remove friction to use the model on Replicate.

**Comment by vladimarius** [comment]
I guess I don't understand how it works then :(
Your image contains hard-coded string as HF token and there is no way to provide it when calling replicate via their API
(I am using their API and I am not running it locally)

**Comment by thomasmol** [comment]
that is correct, the image has my own HF token hard-coded. When you are using the replicate api, you are essentially using my HF token

**Comment by vladimarius** [comment]
I think it is unusual but I get it now :)
I am seeing very low speaker diarization quality which doesn't happen when using pyannotate via API. I thought it was connected to incorrect HF token, now it looks like their free model version is quite different from the paid one. 

It is not related to the topic of my issue, but I am interested in whether you have experienced the same with languages other than English ?

Anyway, thank you very much for your time!
Closing the issue
