### ISSUE TITLE
[FEATURE REQUEST] Add Batched faster-whisper

### ISSUE THREAD

**Issue by NickNaskida** [thomasmol/cog-whisper-diarization#18]
Hey, thanks a lot for your work here! Have you considered using [Batched faster-whisper](https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#batched-faster-whisper)? 

As per docs:

> Batched version improves the speed upto 10-12x compared to openAI implementation and 3-4x compared to the sequential faster_whisper version. It works by transcribing semantically meaningful audio chunks as batches leading to faster inference.

I am down to create a pull request adding this.
Let me know.

**Comment by thomasmol** [comment]
Yes I have seen it! its awesome. however it is not released yet officially as there are a few issues, e.g. https://github.com/SYSTRAN/faster-whisper/pull/940 so i'll wait until an official new release to add this.

**Comment by NickNaskida** [comment]
Cool, I'll deploy my own until then

**Comment by NickNaskida** [comment]
If anyone needs it, it is here: https://replicate.com/nicknaskida/whisper-diarization

Closing this issue for now.
