### ISSUE TITLE
Feature Request: Addition of Phonetic Sounds to Word Transcriptions

### ISSUE THREAD

**Issue by darkw3bb** [thomasmol/cog-whisper-diarization#2]
Hello,

I've been using the cog-whisper-diarization tool and it's been extremely helpful. I have a feature request that I believe could enhance its utility, particularly for applications like lip-syncing models.

**Feature Description:**
I'd like to suggest adding functionality to return the phonetic sounds of words along with their transcriptions. This would involve breaking down each word into its phonetic components and providing timestamps for each phonetic element.

Use Case:
This feature would be incredibly valuable for creating accurate lip-syncing models, as it would provide precise details of how each word is pronounced.

I understand that implementing this feature might be complex, but I believe it would significantly enhance the capabilities of the tool. I'm currently adding these details artificially using GPT, but having this as an integrated feature would be more efficient and powerful.

Thank you for considering this request. I look forward to your thoughts on this.

**Example:**
```json
{
  "end": 2.22,
  "start": 2.04,
  "word": "City",
  "phonetics": [
    {"start": 2.04, "end": 2.12, "mouthShape": "S_shape"},
    {"start": 2.12, "end": 2.17, "mouthShape": "EE_shape"},
    {"start": 2.17, "end": 2.22, "mouthShape": "T_shape"}
  ]
},
{
  "end": 2.5,
  "start": 2.22,
  "word": "need",
  "phonetics": [
    {"start": 2.22, "end": 2.3, "mouthShape": "N_shape"},
    {"start": 2.3, "end": 2.4, "mouthShape": "EE_shape"},
    {"start": 2.4, "end": 2.5, "mouthShape": "D_shape"}
  ]
}

**Comment by thomasmol** [comment]
interesting suggestion! do you have a library/model that can detect the phonetics?

**Comment by darkw3bb** [comment]
We actually used GPT to guess what it would be.

-----------
Thomas Webb
-----------

CEO

Founder | Webb Technology

https://webb.game ( https://webb.game/ )
