### ISSUE TITLE
Large-v3 hallucination problems

### ISSUE THREAD

**Issue by MaximeDde** [thomasmol/cog-whisper-diarization#4]
Hello Thomas, and thanks again for this great cog ! 

I've been finding more and more problems with the large-v3 model though - much more hallucinations than with large-v2, and a global precision really, really lower than with its predecessor. (I've seen it documented in several places, I can find the links again for you but https://deepgram.com/learn/whisper-v3-results this article went the more in-depth I believe).

Do you think there could be a way to have this cog with the large-v2 model instead ? If that doesn't mean too much work on your side !!

**Comment by thomasmol** [comment]
Hi there, thanks!
I know it's a common problem unfortunately. I just pushed an update so the model uses a new version of faster-whisper (1.0.1) which should mitigate the problems with v3 over v2. Let me know if it fixes it for you!

**Comment by MaximeDde** [comment]
I'll give it a try and give feedback here, thank you for the update !

**Comment by thomasmol** [comment]
had to revert back to an older version of faster-whisper unfortunately, seems to be an issue with inference speed of the diarization. probably because of some conflicting python/cuda packages. will update when this is fixed

**Comment by MaximeDde** [comment]
Yes, I saw that... I reverted back to the version just before :( Hopefully they can solve this soon ! Could you please keep me posted ?

**Comment by thomasmol** [comment]
yes will do!

**Comment by thomasmol** [comment]
@MaximeDde. I just updated the model to use the latest `faster-whisper` (1.0.3), which uses a much improved VAD: Silero VAD 5. Hallucinations should be reduced by a lot. Also managed to fix the performance issue with pyannote.audio.
Let me know if you see any improvements!

**Comment by thomasmol** [comment]
closing this for now. reporting back if there are still major issues or better VADs!
