### ISSUE TITLE
[FEATURE REQUEST] Flash Attention 2

### ISSUE THREAD

**Issue by pointia** [thomasmol/cog-whisper-diarization#5]
Hi,

have you ever thought about implementing Flash Attention 2 as well, like here?

https://github.com/Vaibhavs10/insanely-fast-whisper

**Comment by thomasmol** [comment]
yes i have. however, the repo you're linking uses the huggingface api of whisper. unfortunately the huggingface api does not (yet) provide some features like an input for `initial_prompt` and returning the detected language. once it does, i will probably switch since it is much faster.

**Comment by NickNaskida** [comment]
https://github.com/huggingface/distil-whisper/issues/20

Found this, looks like the prompting is supported already.

**Comment by NickNaskida** [comment]
Actually, I believe it is possible, judging from these links:

https://huggingface.co/openai/whisper-large-v3/discussions/128#666af9e88b12eb564be39cdb
https://huggingface.co/distil-whisper/distil-large-v3/discussions/6#666aed28491c9ff1e783d7de

**Comment by NickNaskida** [comment]
Btw, same for language detection:

https://huggingface.co/openai/whisper-large-v3/discussions/15#6554e55dffc7b280f57faf78
