### ISSUE TITLE
Getting long segments

### ISSUE THREAD

**Issue by learner0333** [thomasmol/cog-whisper-diarization#7]
I have tried to get diarized data using your package on Replicate.
I am using group_segments = False . I noticed that for some of the video, I still get the that segment index of 30 seconds. I want to get it for 4 to 5 seconds in each segment.  is it possible?

**Comment by thomasmol** [comment]
if you set the `transcript_output_format` to `both` or `words_only` you get word level timestamps. Then you can write a script to create new segments with your desired config (like creating shorter segments). The word level segments contain punctuation as well so you can just e.g. `.join('')` on them to create a readable sentence.

**Comment by thomasmol** [comment]
.
